title: JinHao Chen's Homepage
page-top-title: JinHao Chen
top-section-bg-text: Remote Sensing
home-subtitle: JinHao Chen&ensp;|&ensp;陈锦昊
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
